In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

In [3]:
a = tf.constant(10)

In [4]:
b= tf.constant(20)

## we can perform operations

In [20]:
a*b

<tf.Tensor: shape=(), dtype=int32, numpy=200>

## or the same with universsal functions

In [21]:
tf.multiply(a,b).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=200>>

In [16]:
tf.executing_eagerly()

True

## we can create variables

In [27]:
x = tf.Variable(2.)

In [28]:
x.assign(10)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=10.0>

In [29]:
print("Original value:",x.numpy())
print("add 1:",x.assign_add(1.).numpy())
print('subtract 5:',x.assign_sub(5).numpy())

Original value: 10.0
add 1: 11.0
subtract 5: 6.0


## matrices

In [24]:
mat_a = tf.constant([[10,20],[39,48]])
mat_b = tf.constant([[28,58],[29,92]])

In [25]:
tf.matmul(mat_a,mat_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 860, 2420],
       [2484, 6678]])>

## Numpy vs TensorFLow